### PR TITLE
upgrade `extract-text-webpack-plugin` to ^2.0.0-beta to fix webpack ^2.0 issue(webpack/extract-text-webpack-plugin#210)

### PR DESCRIPTION
**Pull request by JounQin**

### CODE REVIEW

**Comment by hung-phan** [comment]
Thanks @JounQin. Can you squash these commit? I can cherrypick it to 2 other branches.

**Comment by JounQin** [comment]
Sorry? I don't understand your suggestion, what should I do then?

**Comment by hung-phan** [comment]
Oh, no worry. The PR looks great. I just one all the changes in 1 commit instead of 4. Here is a guide on how to do [squash](https://davidwalsh.name/squash-commits-git). Sorry for any inconvenience. The reason is that I have 3 branches with different features at the moment. I want to use your change across other branches. After merging this, I will apply it into 2 other branches.

**Comment by hung-phan** [comment]
I can help you squash these commits if you want to

**Comment by JounQin** [comment]
Please check whether I did it correctly or help me doing it, thx.

**Comment by hung-phan** [comment]
Oh, no worry. Let me merge this one.

**Pull request merged**
