### PR TITLE
Refactor/sails like config - DO NOT MERGE

### PR DESCRIPTION
**Pull request by tungv**
notes:
- config will be moved to root
- engine will be moved to root (or exposed as an npm package)

to start: `node --harmony ./build/server.js`

### CODE REVIEW

**Comment by tungv** [comment]
@hung-phan please take a look

**Comment by hung-phan** [comment]
:+1:. I also do structure code yesterday to tackle this problem. Also have a suggestion on `https://github.com/hung-phan/all-hail-the-R/blob/master/config%2Finitializers%2Fmiddlewares.js`. Let discuss more on this

**Comment by tungv** [comment]
Cool! similar ideas. However, being able to inject config to engine can make it easier to test

```js

const inject = {
  http: {
    middlewares: {
      bodyParser: false
    }
  }
}
const engine = new Engine(inject)
```

**Comment by hung-phan** [comment]
`https://github.com/hung-phan/all-hail-the-R/issues/3`

**Comment by tungv** [comment]
should we go for this one?
@nqbao @hung-phan

**Comment by nqbao** [comment]
Hey @tungv, the logger looks good. can we separate it to different PR?

**Comment by tungv** [comment]
@nqbao easy, just a few line of code. You can just include `log4js` npm package. I think you can start using it now without a PR

**Pull request closed without merging**
